<a href="https://colab.research.google.com/github/humairaneha/Learning-Pytorch/blob/main/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Autograd
Autograd  provides automatic differentiation for tensor operations. It enables gradient computation, which is essential for training machine learning models using optimization alogrihtms like gradient descent


In [1]:
import torch

In [26]:
x = torch.tensor(3.0,requires_grad=True)  #scalar tensor , bu default requires_grad= False
z= torch.tensor(2.0,requires_grad=True)
y= x**2 + z**4


In [27]:
print(x,y) # grad_fn = <PowBackward0 )# internally computes computational graph x->sq->y: forward,  y->sq->x : backward ( grad )

tensor(3., requires_grad=True) tensor(25., grad_fn=<AddBackward0>)


In [28]:
# run backward propagation from y

y.backward()

In [29]:
# find gradient w.r.t x
x.grad
# find gradient w.r.t z
z.grad

tensor(32.)

In [36]:
x = torch.tensor(3.0,requires_grad=True)
y=x**2
z= torch.sin(y)
z.backward()
x.grad
#y.grad can't compute this. y is internal nodes in the computational graph

tensor(-5.4668)

In [46]:
# for a perceptron
# x: cgpa , y: placement
x = torch.tensor(3.5 , requires_grad=True)
b= torch.tensor(1.0, requires_grad=True)
w = torch.rand(1, requires_grad=True)
z = w*x + b
print(z)
# activation function
y_pred = torch.sigmoid(z)
y_target = 1
loss= - (y_target*torch.log(y_pred) + (1-y_target)*torch.log(1-y_pred))
loss.backward()
print(w.grad)
print(b.grad)

w = w+ w.grad
b=b+b.grad

print(w,b)

tensor([4.1487], grad_fn=<AddBackward0>)
tensor([-0.0544])
tensor(-0.0155)
tensor([0.8452], grad_fn=<AddBackward0>) tensor(0.9845, grad_fn=<AddBackward0>)


In [48]:
# clearing grad , # for multiple time backward operation gradient accumulates with new pass, so we will not get actual value
x.grad.zero_()

tensor(0.)

In [ ]:
# disbale gradienrt tracking
# ex: during inference time we only do forward pass
#option 1 - requires_grad_(False)
# option 2 - detach()
#option 3 - torch.no_grad()