<a href="https://colab.research.google.com/github/humairaneha/Learning-Pytorch/blob/main/PyTorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#NN module
# Building the neural network with NN module
# Using built-in activation function
# Using built-in loss function
# Using built-in optimizer

In [31]:
# model with single neuron
# 5 features and 1 output

# create model class

import torch
import torch.nn as nn

class Model(nn.Module): # inherit from the nn.Module class
  def __init__(self,num_features):
    super().__init__()
    # create layers
    self.linear = nn.Linear(num_features,1) # no of inputs and no of outputs(no of neurons)
    # activation function
    self.sigmoid = nn.Sigmoid()

  # forward pass

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [32]:
# create dummy dataset

features = torch.rand(10,5) # 5 features

# create model instance

model = Model(features.shape[1])

# call model for forward pass

# model.forward(features) : this is not recommended\

model(features) # auto call forward ( overrides __call__ method)


tensor([[0.4058],
        [0.3645],
        [0.3431],
        [0.4292],
        [0.3352],
        [0.3479],
        [0.4387],
        [0.5085],
        [0.3470],
        [0.3819]], grad_fn=<SigmoidBackward0>)

In [33]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.4243, -0.4153, -0.2913,  0.0173, -0.3617]], requires_grad=True)

In [34]:
model.linear.bias

Parameter containing:
tensor([0.2166], requires_grad=True)

In [35]:
# To viaulaize the model

# install the library

!pip install torchinfo

In [36]:
from torchinfo import summary
summary(model, input_size = (10,5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [37]:
# we will create a model with 1 hidden layer and 1 output layer

# 5 input -> 3 neurons (15 weights and 3 bias) -> 1 output neuron ( 3* 1 weights) (1 bias)

# weight matrix size will be (3*5)

class Model_2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # hidden layer 1
    self.hidden_layer = nn.Linear(num_features,3) # 3 neurons
    self.relu = nn.ReLU()
    # output layer
    self.out_layer =  nn.Linear ( 3, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    hidden_out = self.hidden_layer(features)
    hidden_out = self.relu(hidden_out)
    out = self.out_layer(hidden_out)
    out = self.sigmoid(out)
    return out




In [38]:
model_2 =Model_2(features.shape[1])
print(model_2(features))

print(summary(model_2, input_size = (10,5)))

tensor([[0.5013],
        [0.4934],
        [0.4997],
        [0.5013],
        [0.4971],
        [0.4948],
        [0.4947],
        [0.5007],
        [0.4980],
        [0.5003]], grad_fn=<SigmoidBackward0>)
Layer (type:depth-idx)                   Output Shape              Param #
Model_2                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


In [39]:
# simplifying the forwards pass with nn.Sequential container

class Model_2(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
    nn.Linear(num_features,3), # 3 neurons
    nn.ReLU(),
    nn.Linear( 3, 1),
    nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)
    return out


In [40]:
model_2 =Model_2(features.shape[1])
print(model_2(features))

print(summary(model_2, input_size = (10,5)))

tensor([[0.5948],
        [0.5934],
        [0.5992],
        [0.5934],
        [0.5961],
        [0.5958],
        [0.5943],
        [0.5934],
        [0.5936],
        [0.5934]], grad_fn=<SigmoidBackward0>)
Layer (type:depth-idx)                   Output Shape              Param #
Model_2                                  [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
