<a href="https://colab.research.google.com/github/humairaneha/Learning-Pytorch/blob/main/tensor_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.11.0+cpu'

In [ ]:
if torch.cuda.is_available():
  print("using gpu", torch.cuda.get_device_name(0))
else:
  print("using cpu")

using gpu Tesla T4


**Creating a Tensor**


In [ ]:
p = torch.empty(2,3) # allocates memory for tensors but doesn't assign any values
# shows the already exisitng values in the memory cells.

In [ ]:
type(p)

torch.Tensor

In [ ]:
torch.zeros(2,3) # fill with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,4)

tensor([[0.4022, 0.2233, 0.2818, 0.5599],
        [0.6917, 0.6644, 0.8830, 0.7234]])

In [ ]:
#using seed
torch.rand(2,4)

tensor([[0.2685, 0.7545, 0.9936, 0.1714],
        [0.5399, 0.1036, 0.7769, 0.7113]])

In [ ]:
#use manual seed
torch.manual_seed(42)
torch.rand(2,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [ ]:
#using tensor
a = [[1,2,3],[2,3,4]]
type(a)
b=torch.tensor(a)
type(b)

torch.Tensor

In [ ]:
torch.arange(0,10) #1D Tensor with values from start rang to end range ( exclusive)
torch.arange(0,10,2) # incremental

tensor([0, 2, 4, 6, 8])

In [ ]:
#1-dimensional tensor with a specified number of elements (10 in this case),
#evenly spaced between a start value (0) and an end value (10), inclusive.
#So it generates 10 points between 0 and 10 (including both 0 and 10).
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5) #identity matrix of (5*5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
'''function creates a tensor of size (3,3) (meaning 3 rows and 3 columns)
and fills all of its elements with the value 5.'''
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
b.shape

torch.Size([2, 3])

In [ ]:
torch.empty(b.shape)

tensor([[1.6397e-38, 0.0000e+00, 2.3766e-24],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.empty_like(b)

tensor([[139175730171264,       407330384,        11658048],
        [139170084906656, 139175722602192, 139170089558768]])

In [ ]:
torch.ones_like(b)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.zeros_like(b)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([0.1226, 0.8612, 0.3555])

# Data Type


In [ ]:
x = torch.tensor([1,2,3])
x.dtype

torch.int64

In [ ]:
x= torch.tensor([1,2,3], dtype=torch.int64)
x.dtype


torch.int64

In [ ]:
#using .to( ). we convert dtype

x.to(torch.float64)


tensor([1., 2., 3.], dtype=torch.float64)

# Mathemetical Operation on Tensors

In [ ]:
# scalar add
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)
print(x+2)

#scalar  sub

print(x-2)

#mul

print(x*2)

#div

print(x/2)
#int div
print(x//2)

#pow

print(x**2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[2.8823, 2.9150, 2.3829],
        [2.9593, 2.3904, 2.6009]])
tensor([[-1.1177, -1.0850, -1.6171],
        [-1.0407, -1.6096, -1.3991]])
tensor([[1.7645, 1.8300, 0.7657],
        [1.9186, 0.7809, 1.2018]])
tensor([[0.4411, 0.4575, 0.1914],
        [0.4797, 0.1952, 0.3004]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7784, 0.8372, 0.1466],
        [0.9203, 0.1524, 0.3611]])


# Element wise Operation


In [ ]:
a = torch.tensor([[-1,2,3],[4,5,6]])
b= torch.tensor([[1,1,1],[2,2,2]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)
#any type of comaprison operation

#abs
print(torch.abs(a))
#negative
print( torch.neg(b))

tensor([[0, 3, 4],
        [6, 7, 8]])
tensor([[-2,  1,  2],
        [ 2,  3,  4]])
tensor([[-1,  2,  3],
        [ 8, 10, 12]])
tensor([[-1.0000,  2.0000,  3.0000],
        [ 2.0000,  2.5000,  3.0000]])
tensor([[-1,  2,  3],
        [ 2,  2,  3]])
tensor([[-1,  2,  3],
        [16, 25, 36]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[-1, -1, -1],
        [-2, -2, -2]])


In [ ]:
#round
c= torch.tensor([1.9, 2.5, 2.3, 3.7,4.4])
print(torch.round(c))
print(torch.floor(c))
print(torch.ceil(c))
print(torch.clamp(c, min=2,max=3)) # fixed range

tensor([2., 2., 2., 4., 4.])
tensor([1., 2., 2., 3., 4.])
tensor([2., 3., 3., 4., 5.])
tensor([2.0000, 2.5000, 2.3000, 3.0000, 3.0000])


# Reduction Operation

In [ ]:
e= torch.randint(low=0,high=10,size=(2,3)) #This function generates a tensor filled with random integers.
print(e)

tensor([[7, 6, 9],
        [6, 3, 1]])


In [ ]:
#sum
print(torch.sum(e))
#sum along columns
print(torch.sum(e,dim=0)) #reducing row
#sum along rows
print(torch.sum(e,dim=1)) #reducing column

tensor(17)
tensor([2, 9, 6])
tensor([ 5, 12])


In [ ]:
#mean ( to calculate mean we need to have long type)
print(torch.mean(e,dtype=torch.float32))
#mean along col
print(torch.mean(e,dtype=torch.float32,dim=0))
#mean along row
print(torch.mean(e,dtype=torch.float32,dim=1))

tensor(2.8333)
tensor([1.0000, 4.5000, 3.0000])
tensor([1.6667, 4.0000])


In [ ]:
#meadian
torch.median(e)
#max and min
print(torch.max(e))
print(torch.min(e))
print(torch.argmax(e))
print(torch.argmin(e))

tensor(5)
tensor(0)
tensor(4)
tensor(0)


In [ ]:
#statistical operation
# standard deviation
torch.std(e.to(torch.float32))
torch.var(e.to(torch.float32))

tensor(8.2667)

# Matrix operations


In [ ]:
f = torch.tensor([[1,2,3],[4,5,6]] , dtype= torch.float32)
g = torch.tensor([[1,1],[2,2],[3,3]] , dtype= torch.float32)

In [ ]:
#matrix multiplication
k =torch.matmul(f,g)

In [ ]:
#scalar dot product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])
torch.dot(vec1,vec2)

tensor(32)

In [ ]:
#transpose
torch.manual_seed(42)
x=torch.randn(size=(3,3))
print(x)
torch.transpose(x,0,1)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

In [ ]:
#determinant
torch.det(k)
#inverse matrix
p = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
torch.inverse(p)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [ ]:
#special functions
torch.manual_seed(42)

func = torch.randn(2,3)
print(func)

# log

print( torch.log(func) )

#exp

print(torch.exp(func))

#sqrt

print(torch.sqrt(func))

#sigmoid

print(torch.sigmoid(func))

#softmax
print(torch.softmax(func,dim=1))

#relu
print(torch.relu(func))

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
tensor([[-1.0886, -2.0494, -1.4505],
        [-1.4682,     nan,     nan]])
tensor([[1.4003, 1.1375, 1.2642],
        [1.2590, 0.3253, 0.8300]])
tensor([[0.5803, 0.3589, 0.4842],
        [0.4799,    nan,    nan]])
tensor([[0.5834, 0.5322, 0.5583],
        [0.5573, 0.2455, 0.4536]])
tensor([[0.3683, 0.2992, 0.3325],
        [0.5215, 0.1348, 0.3438]])
tensor([[0.3367, 0.1288, 0.2345],
        [0.2303, 0.0000, 0.0000]])


#Inplace Operations


In [ ]:
m = torch.rand(2,3)
n= torch.rand(2,3)
m.add_(n)
m.relu_()

tensor([[1.5295, 0.9792, 1.4407],
        [0.9255, 0.9720, 1.1734]])

In [ ]:
#Copying a Tensor

a= torch.rand(2,3)
b=a
b[0][0]=1;
a[0][0]
print(id(b))
print(id(a))

134401089708480
134401089708480


In [ ]:
c= torch.clone(a)
c[0][0]=5
a[0][0]

tensor(1.)

#Tensor operations on GPU


In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda') # storing gpu device

In [ ]:
#creating a new tensor to gpu
torch.rand((2,3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [ ]:
#moving existing tensor to GPU
a = torch.rand(2,3) # on cpu
b = a.to(device)
b+5

tensor([[5.9811, 5.0874, 5.0041],
        [5.1088, 5.1637, 5.7025]], device='cuda:0')

In [ ]:
import time

size = 10000

# tensors on CPU
mat_cpu1 = torch.randn(size,size)
mat_cpu2 = torch.randn(size,size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(mat_cpu1,mat_cpu2)
cpu_time = time.time() - start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")

mat_gpu1 = mat_cpu1.to(device)
mat_gpu2 = mat_cpu2.to(device)

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(mat_gpu1,mat_gpu2)
torch.cuda.synchronize() # ensure all gpu operations are complete

gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")

print(cpu_time/gpu_time)


Time on CPU: 32.3545 seconds


AssertionError: Torch not compiled with CUDA enabled

# Reshaping tensors


In [ ]:
a= torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape

a.reshape(2,8) # new shape
a.reshape(2,2,2,2) # new shape

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten -> 1D
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#permute
#reorganize shape
b= torch.rand(2,3,4)
b.permute(2,0,1).shape #indexes


torch.Size([4, 2, 3])

In [ ]:
#unsqueeze
# add another dimension of size 1, to introduce batch dimension,making it compatible with models that expect batched inpu

img = torch.rand(226,226,3)
img.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
c = torch.rand(1,2,3,4)
c.squeeze(0).shape

torch.Size([2, 3, 4])

#NumPy and PyTorch


In [ ]:
import numpy as np

n = torch.tensor([[1,2,3],[4,5,6]])

m = n.numpy()

type(m)

t = torch.from_numpy(m)
type(t)


torch.Tensor